services:
  api:
    build: .
    container_name: pos-api-single
    environment:
      DB_MODE: single
      SINGLE_DSN: postgres://postgres:supersecret@192.168.10.243:5432/pos_single?sslmode=disable
      PORT: "8080"
      JWT_SECRET: change-me-in-production
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure